services:
  backend:
    build: .
    container_name: eschool_container
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/eschool
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=eschool
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
